name: build1

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
          
        
    - name: npm install, build
      run: |
        npm install
        npx lerna bootstrap --hoist
        npm run lint
        npm run build:all

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: /home/runner/work/ArtPlayer-1/ArtPlayer-1/dist

